services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: zeztra-challenge-api
    command: npm start
    volumes:
      - ./dist:/app/zeztra-challenge-api
    ports:
      - "5050:5050"
    links:
      - mongo
